name: PyInstaller build

on: [push]

jobs:
  build_macos64:
    # For commits to the original mac build action see:
    # https://github.com/Thlumyn/clangen/blob/29c9e39fed9a09b8de906f5c3b91dc044fe9b9a5/.github/workflows/main.yml
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.10 x64 with miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
          python-version: "3.10"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Update setuptools and wheel
        run: python -m pip install --upgrade setuptools wheel
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Install Pillow for icon format conversion
        run: python -m pip install --upgrade Pillow
      - name: Install PyInstaller
        run: python -m pip install --upgrade PyInstaller
      - name: Run PyInstaller
        #run: python -m PyInstaller -i resources/images/icon.png --name clangen --windowed --onedir --clean --add-data sprites:sprites --add-data resources:resources --add-data README.md:. main.py
        run: python -m PyInstaller Clangen.spec
      - name: Create archive (.tar.xz)
        run: rm -r dist/Clangen
      - name: Install appdmg
        run: "npm install -g appdmg"
      - name: Generate .dmg
        run: "appdmg appdmg.json Clangen_macOS64.dmg"
      - uses: actions/upload-artifact@v3
        with:
          name: Clangen_macOS64.dmg
          path: Clangen_macOS64.dmg
      - name: Release 
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Clangen_macOS64.dmg
